### ISSUE TITLE
Not Python 3 compatible

### ISSUE THREAD

**Issue by jayvdb** [jaimebuelta/ffind#11]
setup.py [uses](https://github.com/jaimebuelta/ffind/blob/39b4623f6a3c4cbedab1ce6048a2d29e6404b5dc/setup.py#L47) the classifier "Programming Language :: Python :: 3" , however it is clearly not Python 3 compatible:

```
$ ffind
Traceback (most recent call last):
  File "/usr/bin/ffind", line 3, in <module>
    from ffind import ffind
  File "/usr/lib/python3.4/site-packages/ffind/ffind.py", line 124
    print "cannot delete: %s" % str(e)
                            ^
SyntaxError: invalid syntax
```

**Comment by jaimebuelta** [comment]
Hey, 

  That was fixed in HEAD, but I didn't create a new release, so installing from PyPI did not install the latest version. I fixed it.

  Please try again to install, it should be fixed now.

  Thanks

**Comment by jayvdb** [comment]
pip is installing 0.7 , as that is the highest version on:

https://pypi.python.org/simple/ffind/

**Comment by jaimebuelta** [comment]
I fixed an issue on the submission to PyPi. Version 0.9.1 should install fine now.

Will take a look at the rest of the issues after a few days. Happy Christmas!
