### ISSUE TITLE
Command exit status ignored

### ISSUE THREAD

**Issue by jayvdb** [jaimebuelta/ffind#14]
ffind can run a command on each file, however it ignores the exit status of those commands.

For the simplest implementation, it should run the command on all matching files, and return 1 if any command returned a non-zero exit status.

Much more complicated approaches can be implemented, such as failing on the first non-zero exit status, return the highest exit status, etc.

**Comment by jaimebuelta** [comment]
Implemented in commit https://github.com/jaimebuelta/ffind/commit/8d6480123cea458248b0e66316a0e823438fb430
