### ISSUE TITLE
wheel broken

### ISSUE THREAD

**Issue by jayvdb** [jaimebuelta/ffind#21]
When I install the wheel, `ffind` has a odd hashbang, and doesnt work.

$ cat /usr/bin/ffind
```py
#!/usr/local/opt/python/bin/python2.7

from ffind import ffind

if __name__ == '__main__':
    ffind.run()
```
```bash
$ ffind
bash: /usr/bin/ffind: /usr/local/opt/python/bin/python2.7: bad interpreter: No such file or directory

```

which is very strange because `/usr/local/opt/` isnt valid, and has never been valid, on my machine.

https://www.python.org/dev/peps/pep-0427/#recommended-installer-features (and nearby) says that the first line needs to be `#!python`.

I suspect that is why tox in jenkins is remoting dying
https://integration.wikimedia.org/ci/job/tox-jessie/7731/console

**Comment by jaimebuelta** [comment]
Strange, in my machine is 

    #!/usr/bin/env python2.7

    from ffind import ffind

    if __name__ == '__main__':
        ffind.run()

which is the equivalent to the one in /scripts I'll change it, but maybe yours is installed from an older version?

**Comment by jayvdb** [comment]
no, I deleted it before installing to be sure it was from the new wheel.
I havent done much wheel work, so I cant say for sure what is required.  Now is a good time to find out ..  ;-)

**Comment by jaimebuelta** [comment]
New version (1.0.2) submitted into PyPI, I checked that the #!python line gets converted into the defined interpreter (a long path with my local installation)

**Comment by jayvdb** [comment]
Bingo. Fixed after issuing `recheck` to PS20 of https://gerrit.wikimedia.org/r/#/c/260909/

**Comment by jaimebuelta** [comment]
\o/
