### ISSUE TITLE
Provide a --force-ignore-case option

### ISSUE THREAD

**Issue by sametmax** [jaimebuelta/ffind#22]
Auto detection for case matching based on the user writting or not uppercase. Buf if you pipe input to ffind and the inputs contains uppercase and you still wish to be case insensitive, an option would help. Right now, you need to normalize everything you pass to ffind.

**Comment by jaimebuelta** [comment]
Added an option for case insensitivity with -i

PR here https://github.com/jaimebuelta/ffind/pull/25
