### ISSUE TITLE
Fuzzy search (feature request)

### ISSUE THREAD

**Issue by hura** [jaimebuelta/ffind#9]
It would be nice to have fuzzy search. The crude implementation is easy: Just add `.*` between every character. The more advanced part is to buffer all the results and sort them by distance/length such that more relevant files are at the top.

For code it could help to check out https://github.com/junegunn/fzf

**Comment by jaimebuelta** [comment]
This is interesting. fzf seems to be quite advanced, and it definitively seems a very useful tool, and more interactive (which is great in fuzzy searches).
I'd like to keep ffind simple and relevant, adding a parameter to enable fuzzy search seems overkill.
What does it sound to return fuzzy results only if no strict results have been found?

**Comment by hura** [comment]
Yes that's not a bad idea but keep in mind that if people use your ffind in their script they will now get results they don't anticipate which means it'd need a big version jump and a warning. So maybe it's better to not do that automagically and introduce a flag. I do like ffind better than fzf since fzf is a pain to install and ffind is just a wget away. That's why I created this issue so I get to use it on my solaris boxes (Go doesnt' support my solarises and never will)

**Comment by jaimebuelta** [comment]
I've added support for this, using the -f flag.

I've also worked in some performance improvements, will try to tag a new release in a few days.

**Comment by jaimebuelta** [comment]
Added in version 0.8! (just released)
